services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "printing"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass YourSecurePassword --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local